# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangesetWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_quantity', models.IntegerField()),
                ('wrapped_object', picklefield.fields.PickledObjectField(editable=False)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_quantity', models.IntegerField()),
                ('wrapped_object', picklefield.fields.PickledObjectField(editable=False)),
                ('method', models.IntegerField()),
                ('labels', models.ManyToManyField(to='deltasherlock_server.EventLabel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='changesetwrapper',
            name='labels',
            field=models.ManyToManyField(to='deltasherlock_server.EventLabel'),
        ),
    ]
