# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltasherlock_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlabel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
